   \bnfelem{all\_words} & ::= & \bnfelem{TOK\_WORD} \bnfor & \\
                        &     & \bnfelem{TOK\_IDENT} \bnfor & \\
                        &     & \bnfelem{TOK\_GEN\_SYM} \bnfor & \\
                        &     & \bnfelem{TOK\_VAR\_BINDING} \bnfor & \\
                        &     & \bnfelem{TOK\_DATA\_TYPE} \bnfor & \\
                        &     & \bnfelem{TOK\_SCH\_NAME} \bnfor & \\
                        &     & \bnfelem{TOK\_GEN\_SCHEMA} \bnfor & \\
                        &     & \bnfelem{TOK\_EXPR\_FUNC} \bnfor & \\
                        &     & \bnfelem{TOK\_PRED\_FUNC} \bnfor & \\
                        &     & \bnfelem{TOK\_P1FPRE} \bnfor & \\
                        &     & \bnfelem{TOK\_P2FPRE} \bnfor & \\
                        &     & \bnfelem{TOK\_P3FPRE} \bnfor & \\
                        &     & \bnfelem{TOK\_P4FPRE} \bnfor & \\
                        &     & \bnfelem{TOK\_P5FPRE} \bnfor & \\
                        &     & \bnfelem{TOK\_P6FPRE} \bnfor & \\
                        &     & \bnfelem{TOK\_P7FPRE} \bnfor & \\
                        &     & \bnfelem{TOK\_P8FPRE} \bnfor & \\
                        &     & \bnfelem{TOK\_P9FPRE} \bnfor & \\
                        &     & \bnfelem{TOK\_P1FIN} \bnfor & \\
                        &     & \bnfelem{TOK\_P2FIN} \bnfor & \\
                        &     & \bnfelem{TOK\_P3FIN} \bnfor & \\
                        &     & \bnfelem{TOK\_P4FIN} \bnfor & \\
                        &     & \bnfelem{TOK\_P5FIN} \bnfor & \\
                        &     & \bnfelem{TOK\_P6FIN} \bnfor & \\
                        &     & \bnfelem{TOK\_P7FIN} \bnfor & \\
                        &     & \bnfelem{TOK\_P8FIN} \bnfor & \\
                        &     & \bnfelem{TOK\_P9FIN} \bnfor & \\
                        &     & \bnfelem{TOK\_P1FPOST} \bnfor & \\
                        &     & \bnfelem{TOK\_P2FPOST} \bnfor & \\
                        &     & \bnfelem{TOK\_P3FPOST} \bnfor & \\
                        &     & \bnfelem{TOK\_P4FPOST} \bnfor & \\
                        &     & \bnfelem{TOK\_P5FPOST} \bnfor & \\
                        &     & \bnfelem{TOK\_P6FPOST} \bnfor & \\
                        &     & \bnfelem{TOK\_P7FPOST} \bnfor & \\
                        &     & \bnfelem{TOK\_P8FPOST} \bnfor & \\
                        &     & \bnfelem{TOK\_P9FPOST} \bnfor & \\
                        &     & \bnfelem{TOK\_P1RPRE} \bnfor & \\
                        &     & \bnfelem{TOK\_P2RPRE} \bnfor & \\
                        &     & \bnfelem{TOK\_P3RPRE} \bnfor & \\
                        &     & \bnfelem{TOK\_P4RPRE} \bnfor & \\
                        &     & \bnfelem{TOK\_P5RPRE} \bnfor & \\
                        &     & \bnfelem{TOK\_P6RPRE} \bnfor & \\
                        &     & \bnfelem{TOK\_P7RPRE} \bnfor & \\
                        &     & \bnfelem{TOK\_P8RPRE} \bnfor & \\
                        &     & \bnfelem{TOK\_P9RPRE} \bnfor & \\
                        &     & \bnfelem{TOK\_P1RIN} \bnfor & \\
                        &     & \bnfelem{TOK\_P2RIN} \bnfor & \\
                        &     & \bnfelem{TOK\_P3RIN} \bnfor & \\
                        &     & \bnfelem{TOK\_P4RIN} \bnfor & \\
                        &     & \bnfelem{TOK\_P5RIN} \bnfor & \\
                        &     & \bnfelem{TOK\_P6RIN} \bnfor & \\
                        &     & \bnfelem{TOK\_P7RIN} \bnfor & \\
                        &     & \bnfelem{TOK\_P8RIN} \bnfor & \\
                        &     & \bnfelem{TOK\_P9RIN} \bnfor & \\
                        &     & \bnfelem{TOK\_P1RPOST} \bnfor & \\
                        &     & \bnfelem{TOK\_P2RPOST} \bnfor & \\
                        &     & \bnfelem{TOK\_P3RPOST} \bnfor & \\
                        &     & \bnfelem{TOK\_P4RPOST} \bnfor & \\
                        &     & \bnfelem{TOK\_P5RPOST} \bnfor & \\
                        &     & \bnfelem{TOK\_P6RPOST} \bnfor & \\
                        &     & \bnfelem{TOK\_P7RPOST} \bnfor & \\
                        &     & \bnfelem{TOK\_P8RPOST} \bnfor & \\
                        &     & \bnfelem{TOK\_P9RPOST} & \\
