   \bnfelem{exist\_quant} & ::= & \bnfelem{TOK\_EXIST} \bnfelem{TOK\_OCURLY} \bnfelem{decl\_list1} & \\
                          &     & \bnfelem{TOK\_QUEST} \bnfelem{pred\_list0} \bnfelem{TOK\_AT} & \\
                          &     & \bnfelem{pred\_list0} \bnfelem{TOK\_CCURLY} & \\
