   \bnfelem{free} & ::= & \bnfelem{TOK\_FREE\_START} \bnfelem{par\_id} \bnfelem{prop} & \\
                  &     & \bnfelem{free\_list} \bnfelem{TOK\_BLOCK\_END} \bnfor & \\
                  &     & \bnfelem{TOK\_FREE\_START} \bnfelem{par\_id} \bnfelem{free\_list} & \\
                  &     & \bnfelem{TOK\_BLOCK\_END} & \\
