   \bnfelem{sch\_ref} & ::= & \bnfelem{TOK\_SCH\_NAME} \bnfor & \\
                      &     & \bnfelem{TOK\_GEN\_SCHEMA} \bnfelem{TOK\_OSQUARE} & \\
                      &     & \bnfelem{expr\_list} \bnfelem{TOK\_CSQUARE} & \\
