   \bnfelem{set\_comp} & ::= & \bnfelem{TOK\_SET\_COMP} \bnfelem{TOK\_OCURLY} \bnfelem{decl\_list} & \\
                       &     & \bnfelem{TOK\_QUEST} \bnfelem{pred\_list0} \bnfelem{TOK\_AT} & \\
                       &     & \bnfelem{expr} \bnfelem{TOK\_CCURLY} & \\
