   \bnfelem{type\_entry} & ::= & \bnfelem{type\_decl} \bnfelem{TOK\_SEMICOLON} \bnfor & \\
                         &     & \bnfelem{type\_decl} \bnfelem{TOK\_SEMICOLON} \bnfelem{TOK\_POUND} & \\
                         &     & \bnfelem{TOK\_OSQUARE} \bnfelem{post\_props} \bnfelem{TOK\_CSQUARE} & \\
