   \bnfelem{all\_quant} & ::= & \bnfelem{TOK\_ALL} \bnfelem{TOK\_OCURLY} \bnfelem{decl\_list1} & \\
                        &     & \bnfelem{TOK\_QUEST} \bnfelem{pred\_list0} \bnfelem{TOK\_AT} & \\
                        &     & \bnfelem{pred\_list0} \bnfelem{TOK\_CCURLY} & \\
