   \bnfelem{rel\_op} & ::= & \bnfelem{TOK\_IDENT} \bnfelem{expr} \bnfor & \\
                     &     & \bnfelem{expr} \bnfelem{TOK\_IDENT} \bnfelem{expr} \bnfor & \\
                     &     & \bnfelem{expr} \bnfelem{TOK\_IDENT} & \\

