\bnfelem{schema\_app} & ::= & \bnfelem{TOK\_OCURLY} \bnfelem{expr} \bnfelem{TOK\_CCURLY} & \\
                      &     & \bnfelem{expr} \bnfelem{TOK\_OCURLY} \bnfelem{expr} & \\
                      &     & \bnfelem{TOK\_CCURLY} & \\
