   \bnfelem{seq\_disp} & ::= & \bnfelem{TOK\_SEQ\_DISP} \bnfelem{TOK\_OCURLY} \bnfelem{expr\_list1} & \\
                       &     & \bnfelem{TOK\_CCURLY} \bnfor & \\
                       &     & \bnfelem{TOK\_SEQ\_DISP} \bnfelem{TOK\_OCURLY} \bnfelem{TOK\_CCURLY} & \\
